
'use strict';
const CLIENT_ID='1548997506820735099';
const STORAGE_SERVERS='kc_servers_v4';
const STORAGE_ACTIVE='kc_active_v4';
const DAYS=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'];
const defaultModules=[['🎧','Support-System','Warteraum, Voice-Musik und Benachrichtigungen.',true],['🚫','Blacklist','Benutzer sperren und verwalten.',true],['🎵','Musik','Support- und Außerhalb-Musik.',true],['⚡','Moderation','Clear und Moderationsfunktionen.',true],['✦','Embed Builder','Eigene Discord-Embeds erstellen.',true],['📊','Statistiken','Bot-Nutzung anzeigen.',true]];
const defaultCommands=[['/ping','Bot-Latenz anzeigen',true],['/serverinfo','Serverinformationen anzeigen',true],['/userinfo','Benutzerinformationen anzeigen',true],['/clear','Nachrichten löschen',true],['/blacklist add','Benutzer sperren',true],['/blacklist remove','Benutzer entsperren',true],['/blacklist list','Blacklist anzeigen',true]];
const defaultServers=[['KölnCity RP','Hauptserver','koelncity-logo.webp'],['Demo Community','Zweiter Discord-Server','koelncity-logo.webp'],['Gaming Lounge','Dritter Discord-Server','koelncity-logo.webp']];
let servers=loadServers();
let activeServer='KölnCity RP';
if(!servers.some(s=>s[0]===activeServer)) activeServer=servers[0][0];

function safeParse(value,fallback){try{return JSON.parse(value)}catch{return fallback}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadServers(){const v=safeParse(localStorage.getItem(STORAGE_SERVERS),null);return Array.isArray(v)&&v.length?v:clone(defaultServers)}
function safeSetStorage(k,v){try{localStorage.setItem(k,v);return true}catch(e){console.error(e);toast('Speichern fehlgeschlagen – Speicherplatz im Browser ist voll');return false}}
function saveServers(){safeSetStorage(STORAGE_SERVERS,JSON.stringify(servers))}
function key(){return 'kc_cfg_v4_'+encodeURIComponent(activeServer).replace(/%/g,'_')}
function base(){return {name:activeServer,logo:'koelncity-logo.webp',subtitle:'Control Panel',welcome:'Alle Einstellungen dieses Discord-Servers an einem Ort.',botName:'KölnCity RP',botStatus:'Online',activityType:'Spielt',activityText:'KölnCity RP',language:'Deutsch',timezone:'Europe/Berlin',modules:clone(defaultModules),commands:clone(defaultCommands),supportEnabled:true,waitChannel:'',notifyChannel:'',supportRole:'',supportTitle:'🚨 Neue Support-Anfrage',supportText:'Ein Benutzer wartet im Support-Warteraum.',schedule:{Montag:['14:00','22:00'],Dienstag:['14:00','22:00'],Mittwoch:['14:00','22:00'],Donnerstag:['14:00','22:00'],Freitag:['14:00','00:00'],Samstag:['13:00','00:00'],Sonntag:['13:00','20:00']},musicSupport:'',musicOutside:'',volume:70,musicLoop:true,blacklist:[],announcements:{channel:'',title:'📢 Wichtige Ankündigung',text:'',image:'',footer:'KölnCity RP',color:'#ff1717',endpoint:'http://localhost:3000/api/announcements',apiKey:''},moderation:{clear:true,antiSpam:false,antiLinks:false,log:true,warn:true},embed:{title:'🚨 Neue Support-Anfrage',description:'Ein Benutzer wartet im Support-Warteraum.',footer:'KölnCity RP',thumbnail:''},automation:[],roles:{adminRole:'',modRole:'',logChannel:'',welcomeChannel:'',ticketChannel:'',voiceChannel:''},lastChange:new Date().toLocaleString('de-DE')}}
function validColor(v){return /^#[0-9a-fA-F]{6}$/.test(v)}
function normalize(c){const d=base(); c=(c&&typeof c==='object')?c:{}; const out={...d,...c};
 out.name=typeof c.name==='string'&&c.name.trim()?c.name.trim():activeServer; out.logo=typeof c.logo==='string'&&c.logo?c.logo:d.logo;
 out.modules=Array.isArray(c.modules)?c.modules.filter(Array.isArray).map(m=>[String(m[0]??'🧩'),String(m[1]??'Modul'),String(m[2]??''),m[3]!==false]):clone(d.modules);
 out.commands=Array.isArray(c.commands)?c.commands.filter(Array.isArray).map(x=>[String(x[0]??'/command'),String(x[1]??''),x[2]!==false]):clone(d.commands);
 out.schedule={...d.schedule,...(c.schedule&&typeof c.schedule==='object'?c.schedule:{})}; DAYS.forEach(day=>{const v=out.schedule[day];out.schedule[day]=Array.isArray(v)&&v.length>=2?[String(v[0]||'00:00'),String(v[1]||'00:00')]:clone(d.schedule[day])});
 out.blacklist=Array.isArray(c.blacklist)?c.blacklist.filter(x=>x&&typeof x==='object').map(x=>({user:String(x.user??''),reason:String(x.reason??'')})).filter(x=>x.user):[];
 out.moderation={...d.moderation,...(c.moderation&&typeof c.moderation==='object'?c.moderation:{})};
 out.embed={...d.embed,...(c.embed&&typeof c.embed==='object'?c.embed:{})}; out.automation=Array.isArray(c.automation)?c.automation.filter(Boolean).map(a=>({name:String(a.name??'Automation'),action:String(a.action??'Aktion')})):[];
 out.announcements={...d.announcements,...(c.announcements&&typeof c.announcements==='object'?c.announcements:{})}; out.announcements.channel=String(out.announcements.channel||''); out.announcements.title=String(out.announcements.title||''); out.announcements.text=String(out.announcements.text||''); out.announcements.image=String(out.announcements.image||''); out.announcements.footer=String(out.announcements.footer||''); out.announcements.color=validColor(String(out.announcements.color||''))?String(out.announcements.color):d.announcements.color; out.announcements.endpoint=String(out.announcements.endpoint||'http://localhost:3000/api/announcements'); out.announcements.apiKey=String(out.announcements.apiKey||''); out.roles={...d.roles,...(c.roles&&typeof c.roles==='object'?c.roles:{})}; out.volume=Math.max(0,Math.min(100,Number(out.volume)||0)); out.supportEnabled=out.supportEnabled!==false; out.musicLoop=out.musicLoop!==false;
 out.lastChange=typeof out.lastChange==='string'?out.lastChange:d.lastChange; return out;}
function cfg(){let c=safeParse(localStorage.getItem(key()),null);if(!c){c=base();safeSetStorage(key(),JSON.stringify(c));return c}return normalize(c)}
function save(c,quiet=false){c=normalize(c);c.lastChange=new Date().toLocaleString('de-DE');if(safeSetStorage(key(),JSON.stringify(c))){if(!quiet)renderAll();return true}return false}
function fillAnnouncements(){let c=cfg(),a=c.announcements||{};const vals={annChannel:a.channel||'',annTitle:a.title||'📢 Wichtige Ankündigung',annText:a.text||'',annImage:a.image||'',annFooter:a.footer||'KölnCity RP',annColor:a.color||'#ff1717',annEndpoint:a.endpoint||'',annApiKey:a.apiKey||''};Object.entries(vals).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.value=v});previewAnnouncement()}
function previewAnnouncement(){const p=document.getElementById('annPreview');if(!p)return;const title=document.getElementById('annTitle')?.value||'📢 Wichtige Ankündigung',text=document.getElementById('annText')?.value||'Hier siehst du deine Ankündigung.',footer=document.getElementById('annFooter')?.value||'KölnCity RP',img=document.getElementById('annImage')?.value||'';const color=document.getElementById('annColor')?.value||'#ff1717';p.style.borderLeftColor=validColor(color)?color:'#ff1717';p.innerHTML='<b>'+esc(title)+'</b><span>'+esc(text).replace(/\n/g,'<br>')+'</span>'+(img?'<img src="'+esc(img)+'" alt="Ankündigungsbild" style="width:100%;margin-top:12px;border-radius:10px;max-height:220px;object-fit:cover">':'')+'<div class="small" style="margin-top:8px">'+esc(footer)+'</div>'}
function saveAnnouncements(){let c=cfg();c.announcements={channel:document.getElementById('annChannel').value.trim(),title:document.getElementById('annTitle').value.trim(),text:document.getElementById('annText').value,image:document.getElementById('annImage').value.trim(),footer:document.getElementById('annFooter').value.trim(),color:document.getElementById('annColor').value.trim(),endpoint:document.getElementById('annEndpoint').value.trim(),apiKey:document.getElementById('annApiKey').value.trim()};save(c);toast('Ankündigung gespeichert')}
async function sendAnnouncement(){saveAnnouncements();const c=cfg(),a=c.announcements||{};if(!/^\d{17,20}$/.test(a.channel))return toast('Bitte eine gültige Discord Channel-ID eingeben');if(!a.text.trim()&&!a.title.trim())return toast('Bitte Titel oder Nachricht eingeben');if(!a.endpoint)return toast('Bitte die API-Adresse eintragen');if(!a.apiKey)return toast('Bitte den Panel-Key eintragen');let endpoint=a.endpoint.trim().replace(/\/$/,'');if(!/^https?:\/\//i.test(endpoint))return toast('API-Adresse muss mit http:// oder https:// beginnen');const btn=[...document.querySelectorAll('#announcements .top .btn')][0];if(btn){btn.disabled=true;btn.textContent='⏳ Wird gesendet...'}try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Panel-Key':a.apiKey},body:JSON.stringify({server:c.name||activeServer,channelId:a.channel,title:a.title,description:a.text,image:a.image,footer:a.footer,color:a.color})});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||('HTTP '+res.status));toast('✓ Ankündigung wurde erfolgreich in Discord gesendet')}catch(e){console.error(e);toast('Senden fehlgeschlagen: '+(e.message||'API nicht erreichbar'))}finally{if(btn){btn.disabled=false;btn.textContent='🚀 Ankündigung senden'}}}
function captureFormToConfig(){let c=cfg();
 ['botName','botStatus','activityType','activityText','language','timezone'].forEach(id=>{const e=document.getElementById(id);if(e)c[id]=e.value});
 ['waitChannel','notifyChannel','supportRole','supportTitle','supportText'].forEach(id=>{const e=document.getElementById(id);if(e)c[id]=e.value.trim()});
 for(const d of DAYS){const a=document.getElementById('s_'+d),b=document.getElementById('e_'+d);if(a&&b)c.schedule[d]=[a.value,b.value]}
 ['musicSupport','musicOutside'].forEach(id=>{const e=document.getElementById(id);if(e)c[id]=e.value.trim()});
 const vol=document.getElementById('volume');if(vol)c.volume=Math.max(0,Math.min(100,Number(vol.value)||0));
 const annChannel=document.getElementById('annChannel'),annTitle=document.getElementById('annTitle'),annText=document.getElementById('annText'),annImage=document.getElementById('annImage'),annFooter=document.getElementById('annFooter'),annColor=document.getElementById('annColor'),annEndpoint=document.getElementById('annEndpoint'),annApiKey=document.getElementById('annApiKey');if(annChannel&&annTitle&&annText&&annImage&&annFooter&&annColor&&annEndpoint&&annApiKey)c.announcements={...c.announcements,channel:annChannel.value.trim(),title:annTitle.value.trim(),text:annText.value,image:annImage.value.trim(),footer:annFooter.value.trim(),color:validColor(annColor.value.trim())?annColor.value.trim():'#ff1717',endpoint:annEndpoint.value.trim(),apiKey:annApiKey.value.trim()};
 const loop=document.getElementById('musicLoop');if(loop)c.musicLoop=loop.value==='true';
 const et=document.getElementById('et'),ed=document.getElementById('ed'),ef=document.getElementById('ef');if(et&&ed&&ef)c.embed={...c.embed,title:et.value.trim(),description:ed.value,footer:ef.value.trim()};
 ['brandInput','brandSub','brandWelcome'].forEach(id=>{});const bi=document.getElementById('brandInput'),bs=document.getElementById('brandSub'),bw=document.getElementById('brandWelcome');if(bi)c.name=bi.value.trim()||activeServer;if(bs)c.subtitle=bs.value;if(bw)c.welcome=bw.value;
 Object.keys(c.roles).forEach(k=>{const e=document.getElementById(k);if(e)c.roles[k]=e.value.trim()});
 return c}
let saveTimer;function autoSaveForms(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{const active=document.activeElement;const page=document.querySelector('.page.active')?.id;if(['settings','support','music','embeds','branding','roles','announcements'].includes(page)&&active&&active.matches('input:not([type=file]), textarea, select')){return}if(['settings','support','music','embeds','branding','roles','announcements'].includes(page)){save(captureFormToConfig(),true);const st=document.getElementById('saveState');if(st){st.textContent='✓ Automatisch gespeichert';st.classList.add('saved')}}},500)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const x=document.getElementById('toast');if(!x)return;x.textContent=t;x.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>x.style.display='none',2200)}
function go(id,btn){if(id==='servers')id='home';const page=document.getElementById(id);if(!page)return;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));page.classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');else{const nav=[...document.querySelectorAll('.nav button')].find(b=>b.getAttribute('onclick')?.includes("'"+id+"'"));if(nav)nav.classList.add('active')}renderAll()}
function renderServerSelector(){const e=document.getElementById('activeServer');if(e){e.innerHTML='<option>KölnCity RP</option>';e.value='KölnCity RP';}}
function selectServer(n){activeServer='KölnCity RP';localStorage.setItem(STORAGE_ACTIVE,activeServer);renderAll();}
function renderModules(){const c=cfg(),el=document.getElementById('moduleGrid');if(!el)return;el.innerHTML=c.modules.length?c.modules.map((m,i)=>`<div class="card module"><div class="mi">${esc(m[0])}</div><div class="grow"><b>${esc(m[1])}</b><p>${esc(m[2])}</p></div><button class="btn secondary" onclick="editModule(${i})">Bearbeiten</button><div class="switch ${m[3]?'on':''}" onclick="toggleModule(${i})"><i></i></div></div>`).join(''):'<div class="card empty">Keine Module vorhanden.</div>';const n=document.getElementById('moduleCount');if(n)n.textContent=c.modules.filter(m=>m[3]).length}
function toggleModule(i){let c=cfg();if(!c.modules[i])return; c.modules[i][3]=!c.modules[i][3];save(c);toast(c.modules[i][1]+(c.modules[i][3]?' aktiviert':' deaktiviert'))}
function editModule(i){let c=cfg(),m=c.modules[i];if(!m)return;openModal('Modul bearbeiten',`<div class="formgrid"><div class="field"><label>Icon</label><input id="x1" class="input" value="${esc(m[0])}"></div><div class="field"><label>Name</label><input id="x2" class="input" value="${esc(m[1])}"></div><div class="field full"><label>Beschreibung</label><textarea id="x3" rows="3">${esc(m[2])}</textarea></div></div><br><button class="btn" onclick="editModuleSave(${i})">Speichern</button>`)}
function editModuleSave(i){let c=cfg();if(!c.modules[i])return; c.modules[i]=[document.getElementById('x1').value.trim()||'🧩',document.getElementById('x2').value.trim()||'Modul',document.getElementById('x3').value.trim(),c.modules[i][3]];save(c);closeModal();toast('Modul gespeichert')}
function addModule(){let n=document.getElementById('mn').value.trim();if(!n)return toast('Modulname fehlt');let c=cfg();c.modules.push([document.getElementById('mic').value.trim()||'🧩',n,document.getElementById('md').value.trim()||'Eigenes Modul',true]);save(c);document.getElementById('mn').value='';document.getElementById('md').value='';toast('Eigenes Modul erstellt')}
function renderCommands(){let c=cfg(),el=document.getElementById('commandList');if(!el)return;el.innerHTML=c.commands.length?c.commands.map((x,i)=>`<div class="row"><span class="badge">${esc(x[0])}</span><span class="grow small">${esc(x[1])}</span><button class="btn secondary" onclick="editCommand(${i})">Bearbeiten</button><div class="switch ${x[2]?'on':''}" onclick="toggleCommand(${i})"><i></i></div></div>`).join(''):'<div class="empty">Keine Commands vorhanden.</div>';const n=document.getElementById('commandCount');if(n)n.textContent=c.commands.filter(x=>x[2]).length}
function toggleCommand(i){let c=cfg();if(!c.commands[i])return;c.commands[i][2]=!c.commands[i][2];save(c);toast('Command '+(c.commands[i][2]?'aktiviert':'deaktiviert'))}
function openCommand(){openModal('Neuen Command',`<div class="formgrid"><div class="field"><label>Name</label><input id="x1" class="input" placeholder="/ticket"></div><div class="field"><label>Beschreibung</label><input id="x2" class="input" placeholder="Ticket erstellen"></div></div><br><button class="btn" onclick="createCommand()">Erstellen</button>`)}
function createCommand(){let c=cfg(),n=document.getElementById('x1').value.trim();if(!n)return toast('Name fehlt');if(c.commands.some(x=>x[0].toLowerCase()===n.toLowerCase()))return toast('Command existiert bereits');c.commands.push([n,document.getElementById('x2').value.trim()||'Eigener Command',true]);save(c);closeModal();toast('Command erstellt')}
function editCommand(i){let c=cfg(),x=c.commands[i];if(!x)return;openModal('Command bearbeiten',`<div class="formgrid"><div class="field"><label>Name</label><input id="x1" class="input" value="${esc(x[0])}"></div><div class="field"><label>Beschreibung</label><input id="x2" class="input" value="${esc(x[1])}"></div></div><br><button class="btn" onclick="editCommandSave(${i})">Speichern</button>`)}
function editCommandSave(i){let c=cfg();if(!c.commands[i])return;let n=document.getElementById('x1').value.trim();if(!n)return toast('Name fehlt');c.commands[i]=[n,document.getElementById('x2').value.trim(),c.commands[i][2]];save(c);closeModal();toast('Command gespeichert')}
function fillSettings(){let c=cfg();['botName','botStatus','activityType','activityText','language','timezone'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=c[id]||''})}
function saveSettings(){let c=cfg();['botName','botStatus','activityType','activityText','language','timezone'].forEach(id=>c[id]=document.getElementById(id).value);save(c);toast('Bot-Einstellungen gespeichert')}
function toggleBool(prop,el){let c=cfg();c[prop]=!c[prop];if(el)el.classList.toggle('on',c[prop]);save(c)}
function fillSupport(){let c=cfg();['waitChannel','notifyChannel','supportRole','supportTitle','supportText'].forEach(id=>document.getElementById(id).value=c[id]||'');document.getElementById('supportSwitch').classList.toggle('on',c.supportEnabled);document.getElementById('schedule').innerHTML=DAYS.map(d=>{const v=c.schedule[d];return `<div class="row"><b>${d}</b><div style="display:flex;gap:6px"><input id="s_${d}" type="time" class="input" style="width:130px" value="${esc(v[0])}"><input id="e_${d}" type="time" class="input" style="width:130px" value="${esc(v[1])}"></div></div>`}).join('')}
function validTime(v){return /^([01]\d|2[0-3]):[0-5]\d$/.test(v)}
function saveSupport(){let c=cfg();['waitChannel','notifyChannel','supportRole','supportTitle','supportText'].forEach(id=>c[id]=document.getElementById(id).value.trim());for(const d of DAYS){const a=document.getElementById('s_'+d).value,b=document.getElementById('e_'+d).value;if(!validTime(a)||!validTime(b))return toast('Bitte alle Supportzeiten korrekt eingeben');c.schedule[d]=[a,b]}save(c);toast('Support gespeichert')}
function fillMusic(){let c=cfg();['musicSupport','musicOutside','volume'].forEach(id=>document.getElementById(id).value=c[id]);document.getElementById('musicLoop').value=String(c.musicLoop)}
function saveMusic(){let c=cfg();c.musicSupport=document.getElementById('musicSupport').value.trim();c.musicOutside=document.getElementById('musicOutside').value.trim();c.volume=Math.max(0,Math.min(100,Number(document.getElementById('volume').value)||0));c.musicLoop=document.getElementById('musicLoop').value==='true';save(c);toast('Musik gespeichert')}
function renderBlacklist(){let c=cfg(),el=document.getElementById('blacklistList');el.innerHTML=c.blacklist.length?c.blacklist.map((x,i)=>`<div class="row"><span><b>${esc(x.user)}</b><br><span class="small">${esc(x.reason||'Kein Grund')}</span></span><button class="btn red" onclick="removeBlacklist(${i})">Entfernen</button></div>`).join(''):'<div class="empty">Keine Benutzer auf der Blacklist.</div>'}
function openBlacklist(){openModal('Benutzer zur Blacklist',`<div class="field"><label>User-ID</label><input id="x1" class="input" inputmode="numeric"></div><br><div class="field"><label>Grund</label><input id="x2" class="input"></div><br><button class="btn" onclick="createBlacklist()">Hinzufügen</button>`)}
function createBlacklist(){let c=cfg(),u=document.getElementById('x1').value.trim();if(!/^\d{17,20}$/.test(u))return toast('Ungültige Discord User-ID');if(c.blacklist.some(x=>x.user===u))return toast('Benutzer ist bereits auf der Blacklist');c.blacklist.push({user:u,reason:document.getElementById('x2').value.trim()});save(c);closeModal();toast('Benutzer hinzugefügt')}
function removeBlacklist(i){let c=cfg();if(!c.blacklist[i])return;c.blacklist.splice(i,1);save(c);toast('Eintrag entfernt')}
function fillModeration(){let c=cfg();document.getElementById('modSettings').innerHTML=Object.entries({clear:'/clear erlauben',antiSpam:'Anti-Spam',antiLinks:'Link-Filter',log:'Moderations-Logs',warn:'Warnsystem'}).map(([k,t])=>`<div class="checkline"><span><b>${t}</b><br><span class="small">Für ${esc(activeServer)}</span></span><div class="switch ${c.moderation[k]?'on':''}" onclick="toggleMod('${k}',this)"><i></i></div></div>`).join('')}
function toggleMod(k,e){let c=cfg();if(!(k in c.moderation))return;c.moderation[k]=!c.moderation[k];save(c);toast('Moderation geändert')}
function saveModeration(){save(cfg());toast('Moderation gespeichert')}
function previewEmbed(){const p=document.getElementById('embedPreview');if(!p)return;p.innerHTML=`<b>${esc(document.getElementById('et').value||'Embed')}</b><span>${esc(document.getElementById('ed').value||'Vorschau')}</span><div class="small" style="margin-top:8px">${esc(document.getElementById('ef').value||'')}</div>`}
function fillEmbed(){let c=cfg();document.getElementById('et').value=c.embed.title||'';document.getElementById('ed').value=c.embed.description||'';document.getElementById('ef').value=c.embed.footer||'';previewEmbed()}
function saveEmbed(){let c=cfg();c.embed={...c.embed,title:document.getElementById('et').value.trim(),description:document.getElementById('ed').value,footer:document.getElementById('ef').value.trim()};save(c);toast('Embed gespeichert')}
function fillAutomation(){let c=cfg(),el=document.getElementById('automationList');el.innerHTML=c.automation.map((a,i)=>`<div class="row"><span><b>${esc(a.name)}</b><br><span class="small">${esc(a.action)}</span></span><button class="btn red" onclick="removeAutomation(${i})">Löschen</button></div>`).join('')||'<div class="empty">Noch keine Automationen.</div>'}
function removeAutomation(i){let c=cfg();if(!c.automation[i])return;c.automation.splice(i,1);save(c);toast('Automation gelöscht')}
function addAutomation(){openModal('Automation',`<div class="field"><label>Name</label><input id="x1" class="input" placeholder="Willkommensnachricht"></div><br><div class="field"><label>Aktion</label><input id="x2" class="input" placeholder="Sende Nachricht in #welcome"></div><br><button class="btn" onclick="createAutomation()">Erstellen</button>`)}
function createAutomation(){let c=cfg(),n=document.getElementById('x1').value.trim();if(!n)return toast('Name fehlt');c.automation.push({name:n,action:document.getElementById('x2').value.trim()||'Aktion'});save(c);closeModal();toast('Automation erstellt')}
function saveAutomation(){save(cfg());toast('Automatisierung gespeichert')}
function fillBranding(){let c=cfg();document.getElementById('brandInput').value=c.name;document.getElementById('brandSub').value=c.subtitle;document.getElementById('brandWelcome').value=c.welcome;document.getElementById('logoPreview').src=c.logo;document.getElementById('sideLogo').src=c.logo;document.getElementById('brandName').textContent=c.name}
function saveBranding(){let c=cfg(),newName=document.getElementById('brandInput').value.trim()||activeServer;c.name=newName;c.subtitle=document.getElementById('brandSub').value;c.welcome=document.getElementById('brandWelcome').value;c.logo=document.getElementById('logoPreview').src;save(c);toast('Branding gespeichert')}
function changeLogo(e){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return toast('Bitte eine Bilddatei auswählen');if(f.size>10*1024*1024)return toast('Bild darf maximal 10 MB groß sein');const r=new FileReader();r.onerror=()=>toast('Bild konnte nicht gelesen werden');r.onload=()=>{const img=new Image();img.onload=()=>{const max=700,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const cv=document.createElement('canvas');cv.width=w;cv.height=h;const ctx=cv.getContext('2d');ctx.drawImage(img,0,0,w,h);const data=cv.toDataURL('image/webp',0.82);if(data.length>900000)return toast('Logo konnte nicht klein genug gespeichert werden');document.getElementById('logoPreview').src=data;let c=cfg();c.logo=data;save(c);toast('Logo geändert und gespeichert')};img.onerror=()=>toast('Ungültiges Bild');img.src=r.result};r.readAsDataURL(f)}
function fillRoles(){let c=cfg();Object.keys(c.roles).forEach(k=>{const e=document.getElementById(k);if(e)e.value=c.roles[k]||''})}
function saveRoles(){let c=cfg();Object.keys(c.roles).forEach(k=>{const e=document.getElementById(k);if(e)c.roles[k]=e.value.trim()});save(c);toast('Rollen & Kanäle gespeichert')}
function renderServers(){const el=document.getElementById('serverList');if(el)el.innerHTML='<div class="row servercard"><img class="serverlogo" src="'+esc(cfg().logo)+'"><div class="grow"><b>'+esc(cfg().name||'KölnCity RP')+'</b><small>Nur dieser Discord-Server</small></div><span class="badge green">Aktiv</span></div>';const hs=document.getElementById('homeServer');if(hs)hs.textContent=cfg().name||'KölnCity RP'}
function selectServerByIndex(i){go('home');}
function inviteBot(){window.open('https://discord.com/oauth2/authorize?client_id='+encodeURIComponent(CLIENT_ID)+'&scope=bot%20applications.commands&permissions=2147483647','_blank','noopener,noreferrer')}
function exportConfig(){const blob=new Blob([JSON.stringify(cfg(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=activeServer.replace(/[^\w-]+/g,'_')+'-config.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exportiert')}
function importConfig(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();localStorage.setItem(key(),JSON.stringify(normalize(parsed)));renderAll();toast('Backup importiert')}catch{toast('Ungültige oder beschädigte JSON-Datei')}finally{e.target.value=''}};r.onerror=()=>{toast('Datei konnte nicht gelesen werden');e.target.value=''};r.readAsText(f)}
function resetServer(){if(!confirm('Wirklich alle Einstellungen dieses Servers zurücksetzen?'))return;localStorage.removeItem(key());renderAll();toast('Server-Konfiguration zurückgesetzt')}
function openModal(title,html){document.getElementById('mt').textContent=title;document.getElementById('mc').innerHTML=html;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function renderAll(){try{let c=cfg();renderServerSelector();renderServers();renderModules();renderCommands();fillSettings();fillSupport();fillMusic();renderBlacklist();fillModeration();fillEmbed();fillAutomation();fillAnnouncements();fillBranding();fillRoles();document.getElementById('supportState').textContent=c.supportEnabled?'An':'Aus';document.getElementById('lastChange').textContent=c.lastChange;document.getElementById('statModules').textContent=c.modules.filter(x=>x[3]).length;document.getElementById('statModuleBar').style.width=(c.modules.length?Math.round(c.modules.filter(x=>x[3]).length/c.modules.length*100):0)+'%';document.getElementById('statFields').textContent=Object.keys(c).length}catch(err){console.error(err);toast('Panel konnte nicht vollständig geladen werden')}}
document.addEventListener('input',e=>{if(e.target.closest('#announcements'))previewAnnouncement()});
document.addEventListener('change',e=>{if(e.target.matches('input:not([type=file]), textarea, select')){clearTimeout(saveTimer);save(captureFormToConfig(),true);const st=document.getElementById('saveState');if(st){st.textContent='✓ Automatisch gespeichert';st.classList.add('saved')}}});
document.addEventListener('blur',e=>{if(e.target.matches('input:not([type=file]), textarea, select')){clearTimeout(saveTimer);save(captureFormToConfig(),true)}},true);
window.addEventListener('beforeunload',()=>{try{save(captureFormToConfig(),true)}catch{}});
window.addEventListener('storage',e=>{if(e.key===STORAGE_SERVERS||e.key===STORAGE_ACTIVE||e.key===key())renderAll()});
document.getElementById('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
renderAll();
